name: Ready the code and deploy

on:
  pull_request:
    types: opened
    
  push: 
    branches:
      - 'main'
      - 'release/**'

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: copying code
        uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: run tests
        run: yarn test



  build-code:
    runs-on: ubuntu-latest
    needs: test-code
    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: copying code
        uses: actions/checkout@v4


      - name: install dependencies
        run: yarn install --frozen-lockfile

        
      - name: Build the code
        run: yarn build


  deploy-code:
    runs-on: ubuntu-latest
    needs: build-code
    steps:
      - name: Deploy this code
        run: echo "Deploying code to production"

